/**
 * DO NOT EDIT THIS FILE!
 * File automatically generated by
 *   build_tools/sim_object_param_struct_hh.py:240
 */

    #ifndef __PARAMS__YAGSBP__
    #define __PARAMS__YAGSBP__

    
namespace gem5 {
namespace branch_prediction {
class YAGSBP;
} // namespace branch_prediction
} // namespace gem5
#include <cstddef>
#include "base/types.hh"

#include "params/ConditionalPredictor.hh"

namespace gem5
{
struct YAGSBPParams
    : public ConditionalPredictorParams
{
    gem5::branch_prediction::YAGSBP * create() const;
    unsigned global_counter_bits;
    unsigned global_predictor_size;
};

} // namespace gem5

#endif // __PARAMS__YAGSBP__
